version: '3.8'
services:
  app:
    container_name: api-cadastrousuario
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
